<?php


use Illuminate\Support\ServiceProvider;

/**
 * @description
 * @author YaoYao
 * @time 2023/8/14 17:04
 */
class YyAutoCodeServiceProvider extends ServiceProvider
{

    public function boot(){
        $this->loadMigrationsFrom(__DIR__."/../database/migrations");
        $this->publishes([
            __DIR__ . '/config/autocode.php' => config_path('autocode.php'),
        ], 'config');

        $this->publishes([

        ]);

    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }


    private function registerCommands(){
        if (!$this->app->runningInConsole()) {
            return;
        }
        $this->commands([

        ]);


    }

}
